# Generated by Django 2.2 on 2019-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModle', '0002_weathers'),
    ]

    operations = [
        migrations.CreateModel(
            name='dontai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=80)),
                ('img', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=80)),
            ],
        ),
    ]
